version: '3.9'

services:

#post gre --> utiliser debian apparemment, alpine est bugue
  #------------------------- FRONTEND -------------------------
  frontend:
    container_name: frontend
  build:
    context: srcs/frontend/
    dockerfile: Dockerfile
  volumes:
    #a definir

networks:
  transcendance:
  driver: bridge
  name: transcendance_network
